name: 'askgpt'
author: 'megamanics'
description: 'Complete'
branding:
  icon: 'life-buoy'
  color: 'grey-dark'
inputs:
  model:
    description: 'model'
    required: false
    default: 'gpt-4'
  prompt:
    description: 'Prompt to send to the model'
    required: true
  max_tokens:
    description: 'Maximum number of tokens to generate'
    required: false
    default: 200
  temperature:
    description: 'Temperature'
    required: false
    default: 0.6
  top_p:
    description: 'Top p'
    required: false
    default: 1
  frequency_penalty:
    description: 'Frequency penalty'
    required: false
    default: 0
  presence_penalty:
    description: 'Presence penalty'
    required: false
    default: 0
  stop:
    description: 'Stop sequence'
    required: false
    default: '\n'
  n:
    description: 'Number of samples to return'
    required: false
    default: 1
outputs:
  response:
    description: 'response'
runs:
  using: 'node20'
  main: 'dist/index.js'