name: 'askgpt'
author: 'megamanics'
description: 'Complete'
branding:
  icon: 'life-buoy'
  color: 'grey-dark'
inputs:
  token:
    description: 'GITHUB_TOKEN or a PAT.'
    default: ${{ github.token }}
  prompt:
    description: 'Prompt to send to the model'
    required: true
  options:
    description: 'options'
    required: false
    default: "{}"
outputs:
  response:
    description: 'response'
runs:
  using: 'node20'
  main: 'dist/index.js'