name: 'anygpt'
description: 'Complete'
inputs:
  endpoint:
    description: 'Endpoint URL'
    required: true
  apikey:
    description: 'API key'
    required: true
  apiversion:
    description: 'api version'
    required: true
  prompt:
    description: 'Prompt to send to the model'
    required: true
  temperature:
    description: 'Sampling temperature to use'
    required: false
    default: 0.9
  stop:
    description: 'Tokens to stop generation at'
    required: false
    default: ['\n', '###']
outputs:
  response:
    description: 'response'
runs:
  using: 'node16'
  main: 'dist/index.js'