name: release

on: 
  release: 
    types: [published, created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: package
        uses: immutable-actions/publish-immutable-action@main
        with:
          path: 'action.yml dist/'
