name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - uses: ./
      id: generate-response
      with:
        endpoint: ${{ secrets.ENDPOINT }}
        apikey: ${{ secrets.KEY }}
        apiversion: ${{ secrets.VERSION }}
        prompt: 'create a github action haiku'
    - run: echo ${{ steps.generate-response.outputs.response }}

  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npm test