name: "units-test"
on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - uses: ./
      id: multi-prompt
      env:
        ENDPOINT: ${{ secrets.ENDPOINT }}
        KEY: ${{ secrets.KEY }}
      with:
        prompt: '{"prompt": ["what are the important things in life", "rank in order of difficulty.", "pick top 3 and write it as a mardown list."]}'
        max_tokens: 10
    -  env:
        RESPONSE: ${{ steps.multi-prompt.outputs.response }}
       run: echo ${{ env.RESPONSE }} || echo 0

  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - run: npm ci
    - env:
        ENDPOINT: ${{ secrets.ENDPOINT }}
        KEY: ${{ secrets.KEY }}
      run: npm test
